### ISSUE TITLE
Using tuples#concat.

### ISSUE THREAD

**Issue by diasbruno** [fantasyland/fantasy-tuples#3]
Hi, is there a better way of solving this? (and I hope I'm correct on this)...

`Semigroup (a, b) where a, b must be Semigroups`.

So, we have to define:

```javascript
import {concat} from 'fantasy-land';

// data Number a = Number a (??)
// weird and incorrect, but works for simple tuples like (Int, String).
Number.prototype.concat = function(b) { return this + b; };
Number.prototype[concat] = Number.prototype.concat;

// this one I think is reasonable.
String.prototype[concat] = String.prototype.concat;
```

We can now use:

```javascript 
Tuple(1, "a").concat(Tuple(2, "b")) == Tuple(3, "ab")
```

The right way to do it for `Num a` would require.

```javascript
Sum(1).concat(Sum(2))
Prod(1).concat(Prod(2))
```

With the `String.prototype[concat]` snippet all tests passes because `String` implements fantasy-land/Semigroup.

**Comment by safareli** [comment]
I think you want something like this?
```js
String.prototype[concat] = String.prototype.concat;
Touple(Sum(1), "1").concat(Touple(Sum(2), "2")) // Touple(Sum(3), "12")
```

**Comment by diasbruno** [comment]
@safareli I was thinking about the `Number.prototype[concat]`, considering `Number` something like `data Number a = Number a; instance Semigroup Number ...`, but I think it's just a hack to make my life easier.

Thanks for the suggestion.

**Comment by safareli** [comment]
Number has more then one Semigroup instance so that would not quite work I think. even in haskel you need to wrap Num in Sum or Prod to concat them

**Comment by diasbruno** [comment]
Yeah, correct. Thanks @safareli!

**Comment by davidchambers** [comment]
You should use [sanctuary-type-classes][1] to avoid redefining `fantasy-land/concat` for various built-in types, and to avoid mutating global prototype objects. Here's an outline:

```javascript
'use strict';

var FL = require('fantasy-land');
var Z = require('sanctuary-type-classes');

//  Tuple :: (a, b) -> Tuple a b
function Tuple(_1, _2) {
  if (!(this instanceof Tuple)) return new Tuple(_1, _2);
  this._1 = _1;
  this._2 = _2;
}

//  Tuple#toString :: Tuple a b ~> () -> String
Tuple.prototype.toString = function() {
  return 'Tuple(' + Z.toString(this._1) + ', ' + Z.toString(this._2) + ')';
};

//  Tuple#fantasy-land/equals :: Tuple a b ~> Tuple a b -> Boolean
Tuple.prototype[FL.equals] = function(other) {
  return Z.equals(this._1, other._1) && Z.equals(this._2, other._2);
};

//  Tuple#fantasy-land/concat :: (Semigroup a, Semigroup b) => Tuple a b ~> Tuple a b -> Tuple a b
Tuple.prototype[FL.concat] = function(other) {
  return Tuple(Z.concat(this._1, other._1), Z.concat(this._2, other._2));
};

//  Add :: Number -> Add
function Add(n) {
  if (!(this instanceof Add)) return new Add(n);
  this.value = n;
}

//  Add#toString :: Add ~> () -> String
Add.prototype.toString = function() {
  return 'Add(' + Z.toString(this.value) + ')';
};

//  Add#fantasy-land/equals :: Add ~> Add -> Boolean
Add.prototype[FL.equals] = function(other) {
  return Z.equals(this.value, other.value);
};

//  Add#fantasy-land/concat :: Add ~> Add -> Add
Add.prototype[FL.concat] = function(other) {
  return Add(this.value + other.value);
};

Z.concat(Tuple(Add(1), 'a'), Tuple(Add(2), 'b'));
// => Tuple(Add(3), 'ab')

Z.concat(Tuple({x: 1, y: 1}, ['foo', 'bar']), Tuple({y: 2, z: 2}, ['baz']));
// => Tuple({x: 1, y: 2, z: 2}, ['foo', 'bar', 'baz'])
```


[1]: https://github.com/sanctuary-js/sanctuary-type-classes

**Comment by diasbruno** [comment]
@davidchambers This looks really nice!

That would cause confusion, and also, it is wrong (making Number#concat represent `Sum#concat`).

Thanks for the help!

**Comment by davidchambers** [comment]
If you end up defining Sum and Prod types, we could create @fantasyland repositories for them. We'd like to avoid duplicative implementations of algebraic data types for the sake of interoperability.

**Comment by diasbruno** [comment]
They are defined in [fantasy-monoids](https://github.com/fantasyland/fantasy-monoids).

[Addition](https://github.com/fantasyland/fantasy-monoids/blob/master/src/additive.js)
[Multiplicative](https://github.com/fantasyland/fantasy-monoids/blob/master/src/multiplicative.js)

So, I guess I can submit a PR there to add other implementation such as Foldable, Traversable...
